aiVersion: v1
kind: Service
metadata:
  name: mongo-svc-a
  labels:
    name: mongo-svc-a
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-a
  selector:
    name: mongo-node1
    instance: rod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc1
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-node1
  template:
    metadata:
      labels:
        name: mongo-node1
        instance: rod
    spec:
      containers:
      - name: mongo-node1
        image: mongo
        command:
         - mongod
         - "--replSet"
         - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage1
        awsElasticBlockStore:
          volumeID: vol-0f51009cd281a716b
          fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-svc-a
  labels:
    name: ocr-svc-a
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: ocr-svc-a
  selector:
    name: ocr-node1
    instance: jack
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ocr-rc1
  labels:
    name: ocr-rc
spec:
  replicas: 1
  selector:
    name: ocr-node1
  template:
    metadata:
      labels:
        name: ocr-node1
        instance: jack
    spec:
      containers:
      - name: ocr-node1
        image: kylinhuang/teamartizan:latest
        ports:
        - containerPort: 8080
          name: ocr-server
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
        securityContext:
          privileged: true
      volumes:
      - name: cgroup
        emptyDir: {}
