apiVersion: v1
kind: ReplicationController
metadata:
  name: ocr-rc1
  labels:
    name: ocr-rc
spec:
  replicas: 1
  selector:
    name: ocr-node1
  template:
    metadata:
      labels:
        name: ocr-node1
        instance: jack
    spec:
      containers:
      - name: ocr-node1
        image: kylinhuang/teamartizan:latest
        ports:
        - containerPort: 8080
          name: ocr-server
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
        securityContext:
          privileged: true
      volumes:
      - name: cgroup
        emptyDir: {}

