apiVersion: v1
kind: Service
metadata:
  name: ocr-svc-a
  labels:
    name: ocr-svc-a
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: ocr-svc-a
  selector:
    name: ocr-node1
    instance: jack
