apiVersion: v1
kind: ReplicationController
metadata:
  name: ocr-rc1
  labels:
    name: ocr-rc
spec:
  replicas: 1
  selector:
    name: ocr-node1
  template:
    metadata:
      labels:
        name: ocr-node1
        instance: jack
    spec:
      containers:
      - name: ocr-node1
        image: kylinhuang/mcc1:latest
        command:
#         - python3
#         - server.py
#         - my_replica_set
        ports:
        - containerPort: 8080
          name: ocr-server
